-- GASTOS DA CASA - BANCO REVISADO
-- Pode ser executado mesmo depois do SQL anterior.
-- Ele mantém a tabela de gastos e permite que os usuários atuais do projeto
-- compartilhem os mesmos lançamentos com segurança.

create table if not exists public.membros_casal (
  user_id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  criado_em timestamptz not null default now()
);

-- Adiciona como membros todos os usuários que já existem neste projeto.
-- Hoje isso deve incluir você e sua esposa.
insert into public.membros_casal (user_id, nome)
select
  id,
  coalesce(
    nullif(raw_user_meta_data ->> 'display_name', ''),
    split_part(email, '@', 1)
  )
from auth.users
on conflict (user_id) do nothing;

alter table public.membros_casal enable row level security;

drop policy if exists "Membro consulta o proprio cadastro" on public.membros_casal;
create policy "Membro consulta o proprio cadastro"
  on public.membros_casal
  for select
  to authenticated
  using (auth.uid() = user_id);

grant select on table public.membros_casal to authenticated;

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  gasto text not null check (char_length(trim(gasto)) between 1 and 120),
  valor numeric(12,2) not null check (valor > 0),
  forma text not null check (forma in ('PIX', 'BYBIT', 'NUBANK', 'ALELO')),
  ocorrido_em timestamptz not null default now(),
  observacao text check (observacao is null or char_length(observacao) <= 500),
  client_id uuid not null unique,
  criado_em timestamptz not null default now()
);

create index if not exists gastos_user_data_idx
  on public.gastos (user_id, ocorrido_em desc);

create index if not exists gastos_ocorrido_em_idx
  on public.gastos (ocorrido_em desc);

alter table public.gastos enable row level security;

-- Remove as políticas da primeira versão.
drop policy if exists "Usuarios visualizam os proprios gastos" on public.gastos;
drop policy if exists "Usuarios inserem os proprios gastos" on public.gastos;
drop policy if exists "Usuarios atualizam os proprios gastos" on public.gastos;
drop policy if exists "Usuarios excluem os proprios gastos" on public.gastos;

-- Remove as políticas revisadas antes de recriá-las.
drop policy if exists "Membros visualizam os gastos do casal" on public.gastos;
drop policy if exists "Membros inserem gastos" on public.gastos;
drop policy if exists "Membros atualizam gastos" on public.gastos;
drop policy if exists "Membros excluem gastos" on public.gastos;

create policy "Membros visualizam os gastos do casal"
  on public.gastos
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.membros_casal membro
      where membro.user_id = auth.uid()
    )
  );

create policy "Membros inserem gastos"
  on public.gastos
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.membros_casal membro
      where membro.user_id = auth.uid()
    )
  );

create policy "Membros atualizam gastos"
  on public.gastos
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.membros_casal membro
      where membro.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.membros_casal membro
      where membro.user_id = auth.uid()
    )
  );

create policy "Membros excluem gastos"
  on public.gastos
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.membros_casal membro
      where membro.user_id = auth.uid()
    )
  );

grant select, insert, update, delete on table public.gastos to authenticated;
grant usage, select on sequence public.gastos_id_seq to authenticated;

-- Conferência: deve retornar os dois usuários atuais como membros.
select
  m.user_id,
  u.email,
  m.nome,
  m.criado_em
from public.membros_casal m
join auth.users u on u.id = m.user_id
order by m.criado_em;
